### ISSUE TITLE
NFT integration

### ISSUE THREAD

**Issue by Devilla** [muellners/ans-app#5]
## Overview
A domain name can be considered as an NFT, see a domain name can be mapped to an ERC721 token which can be traded between users. Since some domain names can be evaluated as some kind of asset over time and if the owner wants to transfer and get benefitted from that evaluation. So, it should be available as an asset in the form of NFT.

## Method
Write a smart contract that transfer the NFT which is pegged  to a domain name by the owner using the ANS-App, whenever the NFT is transfered between addresses the domain name also get transfered by using `transfer` method of the ANS app.

**Comment by maektwain** [comment]
This issue should not be here, it should be at the Contract, plus the work is already done please check the contract/wrapper
